version: '3.4'

services:
    app:
        build:
            context: .
            target: prod
        environment:
            APP_SECRET:
            DEFAULT_LOCALE:
            SERVICE_NAME:
        image: libero/content-store:${IMAGE_TAG:-master}
        volumes:
            - ./.docker/data:/app/data/
    web:
        image: nginx:1.15.8-alpine
        volumes:
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public/:/app/public/
        ports:
            - 8080:80
        depends_on:
            - app
