parameters:
    env(DEFAULT_LOCALE): 'en'
    env(SERVICE_NAME): 'articles'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Libero\ContentStore\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'
